# Use phusion/baseimage as base image. To make your builds
# reproducible, make sure you lock down to a specific version, not
# to `latest`! See
# https://github.com/phusion/baseimage-docker/blob/master/Changelog.md
# for a list of version numbers.
FROM phusion/baseimage:0.9.16

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

# create go user
RUN ["groupadd", "-r", "go"]
RUN ["useradd", "-r", "-c", "Go User", "-g", "go", "-d", "/var/go", "-m", "-s", "/bin/bash", "go"]
RUN ["mkdir", "-p", "/var/lib/go-server/plugins/external"]

# add plugins
ADD https://github.com/ashwanthkumar/gocd-build-github-pull-requests/releases/download/v1.0/git-fb-poller-1.0.jar  /var/lib/go-server/plugins/external/
ADD https://github.com/ashwanthkumar/gocd-build-github-pull-requests/releases/download/v1.0/github-pr-poller-1.0.jar /var/lib/go-server/plugins/external/
ADD https://github.com/srinivasupadhya/gocd-build-status-notifier/releases/download/v1.0/github-pr-status-1.0.jar /var/lib/go-server/plugins/external/

# create plugin volume for go.cd
RUN ["chown", "-R", "go:go", "/var/lib/go-server/plugins/external"]
VOLUME ["/var/lib/go-server/plugins/external"]

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
